# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: --secure-file-priv=/raw_data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080