-- CREATING THE DATABASE
CREATE DATABASE domestic_flights;

USE domestic_flights;

-- CREATING THE TABLES
CREATE TABLE AIRLINE (IATA_CODE VARCHAR(4), AIRLINE VARCHAR(50));

CREATE TABLE AIRPORT (
    IATA_CODE VARCHAR(4),
    AIRPORT VARCHAR(100),
    CITY VARCHAR(30),
    STATE VARCHAR(15),
    COUNTRY VARCHAR(20),
    LATITUDE VARCHAR(20),
    LONGITUDE VARCHAR(20)
);

CREATE TABLE FLIGHT (
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    DAY_OF_WEEK INTEGER,
    AIRLINE VARCHAR(50),
    FLIGHT_NUMBER INTEGER,
    TAIL_NUMBER VARCHAR(50),
    ORIGIN_AIRPORT VARCHAR(50),
    DESTINATION_AIRPORT VARCHAR(50),
    SCHEDULED_DEPARTURE NUMERIC,
    DEPARTURE_TIME VARCHAR(25),
    DEPARTURE_DELAY VARCHAR(25),
    TAXI_OUT VARCHAR(25),
    WHEELS_OFF VARCHAR(25),
    SCHEDULED_TIME VARCHAR(25),
    ELAPSED_TIME VARCHAR(25),
    AIR_TIME VARCHAR(25),
    DISTANCE VARCHAR(25),
    WHEELS_ON VARCHAR(25),
    TAXI_IN VARCHAR(25),
    SCHEDULED_ARRIVAL VARCHAR(25),
    ARRIVAL_TIME VARCHAR(25),
    ARRIVAL_DELAY VARCHAR(25),
    DIVERTED NUMERIC,
    CANCELLED NUMERIC,
    CANCELLATION_REASON VARCHAR(50),
    AIR_SYSTEM_DELAY VARCHAR(25),
    SECURITY_DELAY VARCHAR(25),
    AIRLINE_DELAY VARCHAR(25),
    LATE_AIRCRAFT_DELAY VARCHAR(25),
    WEATHER_DELAY VARCHAR(25)
);

-- LOADING THE DATA INTO TABLES
LOAD DATA INFILE '/raw_data/airlines.csv' INTO TABLE AIRLINE FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/raw_data/airports.csv' INTO TABLE AIRPORT FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/raw_data/flights.csv' INTO TABLE FLIGHT FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

-- CREATING THE VIEWS (mv sufix == MATERIALIZED VIEW)
CREATE TABLE busiest_day_of_week_mv (DAY_OF_WEEK NUMERIC, NUMBER_OF_FLIGHTS NUMERIC);

CREATE TABLE busiest_airport_mv (AIRPORT VARCHAR(100), NUMBER_OF_FLIGHTS NUMERIC);

CREATE TABLE busiest_state_mv (STATE VARCHAR(15), NUMBER_OF_FLIGHTS NUMERIC);

CREATE TABLE busiest_state_regional_trips_mv (STATE VARCHAR(15), NUMBER_OF_FLIGHTS NUMERIC);

-- INSERT DATA INTO VIEWS
INSERT INTO
    busiest_day_of_week_mv
SELECT
    DAY_OF_WEEK,
    COUNT(*) AS NUMBER_OF_FLIGHTS
FROM
    FLIGHT
GROUP BY
    DAY_OF_WEEK
ORDER BY
    COUNT(*) DESC
LIMIT
    1;

INSERT INTO
    busiest_airport_mv
SELECT
    AIRPORT.AIRPORT,
    COUNT(*) NUMBER_OF_FLIGHTS
FROM
    AIRPORT AS AIRPORT
    INNER JOIN FLIGHT AS FLIGHT ON (AIRPORT.IATA_CODE = FLIGHT.ORIGIN_AIRPORT)
    OR (AIRPORT.IATA_CODE = FLIGHT.DESTINATION_AIRPORT)
GROUP BY
    AIRPORT.AIRPORT
ORDER BY
    COUNT(*) DESC
LIMIT
    1;

INSERT INTO
    busiest_state_mv
SELECT
    AIRPORT.STATE,
    COUNT(*) NUMBER_OF_FLIGHTS
FROM
    AIRPORT AS AIRPORT
    INNER JOIN FLIGHT AS FLIGHT ON (AIRPORT.IATA_CODE = FLIGHT.ORIGIN_AIRPORT)
    OR (AIRPORT.IATA_CODE = FLIGHT.DESTINATION_AIRPORT)
GROUP BY
    AIRPORT.STATE
ORDER BY
    COUNT(*) DESC
LIMIT
    1;

INSERT INTO
    busiest_state_regional_trips_mv
SELECT
    ORIGIN_AIRPORT.STATE,
    COUNT(*) AS NUMBER_OF_FLIGHTS
FROM
    FLIGHT AS FLIGHT
    INNER JOIN AIRPORT AS ORIGIN_AIRPORT ON FLIGHT.ORIGIN_AIRPORT = ORIGIN_AIRPORT.IATA_CODE
    INNER JOIN AIRPORT AS DEST_AIPORT ON FLIGHT.DESTINATION_AIRPORT = DEST_AIPORT.IATA_CODE
WHERE
    ORIGIN_AIRPORT.STATE = DEST_AIPORT.STATE
GROUP BY
    ORIGIN_AIRPORT.STATE
ORDER BY
    COUNT(*) DESC
LIMIT
    1;