CREATE DATABASE domestic_flights;
USE domestic_flights;
CREATE TABLE AIRLINE (IATA_CODE VARCHAR(4), AIRLINE VARCHAR(50));
CREATE TABLE AIRPORT (IATA_CODE VARCHAR(4), AIRPORT VARCHAR(50), 
                      CITY VARCHAR(20), STATE VARCHAR(15), 
                      COUNTRY VARCHAR(20), LATITUDE NUMERIC,
                      LONGITUDE NUMERIC);
CREATE TABLE FLIGHT (YEAR INTEGER, MONTH INTEGER, DAY INTEGER,
                     DAY_OF_WEEK INTEGER, AIRLINE VARCHAR(50), 
                     FLIGHT_NUMBER INTEGER, TAIL_NUMBER VARCHAR(50),
                     ORIGIN_AIRPORT VARCHAR(50), DESTINATION_AIRPORT VARCHAR(50),
                     SCHEDULED_DEPARTURE NUMERIC, DEPARTURE_TIME NUMERIC,
                     DEPARTURE_DELAY NUMERIC, TAXI_OUT NUMERIC,
                     WHEELS_OFF NUMERIC, SCHEDULED_TIME NUMERIC,
                     ELAPSED_TIME NUMERIC, AIR_TIME NUMERIC,
                     DISTANCE NUMERIC, WHEELS_ON NUMERIC, TAXI_IN NUMERIC,
                     SCHEDULED_ARRIVAL NUMERIC, ARRIVAL_TIME NUMERIC, 
                     ARRIVAL_DELAY NUMERIC, DIVERTED NUMERIC,
                     CANCELLED NUMERIC, CANCELLATION_REASON VARCHAR(50),
                     AIR_SYSTEM_DELAY NUMERIC, SECURITY_DELAY NUMERIC,
                     AIRLINE_DELAY NUMERIC, LATE_AIRCRAFT_DELAY NUMERIC,
                     WEATHER_DELAY NUMERIC);