INSERT INTO
    busiest_airport_mv
SELECT
    AIRPORT.AIRPORT,
    COUNT(*) NUMBER_OF_FLIGHTS
FROM
    AIRPORT AS AIRPORT
    INNER JOIN FLIGHT AS FLIGHT ON (AIRPORT.IATA_CODE = FLIGHT.ORIGIN_AIRPORT)
    OR (AIRPORT.IATA_CODE = FLIGHT.DESTINATION_AIRPORT)
GROUP BY
    AIRPORT.AIRPORT
ORDER BY
    COUNT(*) DESC
LIMIT 10;